services:
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=javademos"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
    ports:
      - "5434:5432"
